# Generated by Django 2.0.3 on 2018-03-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20180328_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
